name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Setup npm
        run: npm install -g npm@7
      - name: Install Dependencies
        if: steps.node.outputs.cache-hit != 'true'
        run: npm ci
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Setup npm
        run: npm install -g npm@7
      - name: Build
        run: npm run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Setup npm
        run: npm install -g npm@7
      - name: Lint
        run: npm run lint
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Setup npm
        run: npm install -g npm@7
      - name: Type Check
        run: npm run type-check
